### ISSUE TITLE
Deployment issue with service/db

### ISSUE THREAD

**Issue by DavidFeu** [d-lama/ops-d-lama-service#13]
Link to User Story
[1008](https://github.com/d-lama/.github/blob/main/mgmt/product_backlog.md#1008)

Bug Description
- Pod does not restart when service is deployed:
[d-lama-service-9d45fd8d4-ckgwt_d-lama-service.log](https://github.com/d-lama/ops-d-lama-service/files/11546766/d-lama-service-9d45fd8d4-ckgwt_d-lama-service.log)

**Comment by Yingrjimsch** [comment]
We'v analyzed the issue and concluded that it is not breaking
